insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (1, 'Osobowe', 'Auta małe', 'Audi', 12000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (2, 'Osobowe', 'Auta miejskie', 'BMW', 15500)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (3, 'Osobowe', 'SUV', 'Opel', 23000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (4, 'Osobowe', 'Sedan', 'Ford', 27000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (5, 'Osobowe', 'Coupe', 'Renault', 34000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (6, 'Dostawcze', 'Autolaweta', 'Iveco', 6000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (7, 'Dostawcze', 'Chłodnia', 'Fiat', 8000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (8, 'Dostawcze', 'Kamper', 'Renault', 15000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (9, 'Dostawcze', 'Mikrobus', 'Mercedes-Benz', 6200)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (10, 'Dostawcze', 'Plandeka', 'Opel', 13200)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (11, 'Ciężarowe', 'Autobus', 'Mercedes-Benz', 165000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (12, 'Ciężarowe', 'Ciągnik siodłowy', 'Scania', 76000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (13, 'Ciężarowe', 'Cysterna', 'MAN', 67000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (14, 'Ciężarowe', 'Kontener', 'Volvo', 90000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (15, 'Ciężarowe', 'Pompa do betonu', 'MAN', 255000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (16, 'Budowlane', 'Koparki kołowe', 'Schaeff', 189000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (17, 'Budowlane', 'Minikoparki', 'Caterpillar', 104900)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (18, 'Budowlane', 'Podnośniki', 'MAN', 60000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (19, 'Budowlane', 'Ładowarki', 'Everun', 41000)
insert into Car (ID, TYP, NADWOZIE, MARKA, CENA) values (20, 'Budowlane', 'Ładowarka teleskopowa', 'Manitou', 33000)
